$(function()
{
    $('.login').click(function(){
        $('.login-modal-wrapper').fadeIn();
        //alert("hogehoge");
    });

    $('.signup-show').click(function(){
        $('.signup-modal-wrapper').fadeIn();
    });
    $('.close-modal').click(function(){
        $('.login-modal-wrapper').fadeOut();
        $('.signup-modal-wrapper').fadeOut();
    });
    $(this).find('.text-contents').addClass('text-active');
    $('.lesson-hover').hover(function(){
    },
    function(){
        $(this).find('.text-contents').removeClass('text-active');
    }
    );
    $('.faq-list-item').click(function(){
        var $answer = $(this).find('.answer');
        if($answer.hasClass('open'))
        {
            $answer.removeClass('open');
            $answer.slideUp();
            $(this).find('span').text('+');
        }
        else
        {
            $answer.addClass('open');
            $answer.slideDown();
            $(this).find('span').text('-');
        }
    });
});